TEXT_OK             Ok
TEXT_CANCEL         Cancel
TEXT_COLUMNS        Columns
TEXT_ROWS           Rows
TEXT_NEW_LABEL      A new label will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_BUTTON     A new push button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_CHECK      A new check box will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_RADIO      A new radio button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_TOOL       A new tool button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_POPUP      A new popup button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_ELEM_POPUP A new element will be added to popup in cell '%s'
TEXT_NEW_ELEM_LIST  A new element will be added to listbox in cell '%s'
TEXT_NEW_EDIT       A new editbox will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_COMBO      A new combo box will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_LISTBOX    A new listbox will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_SLIDER     A new slider will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_VSLIDER    A new vertical slider will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_SUBLAYOUT  A new sublayout will be placed in cell (%d, %d) of '%s' layout
TEXT_LAYOUT_PROPS   Layout properties
TEXT_COLUMN_PROPS   Column properties
TEXT_ROW_PROPS      Row properties
TEXT_CELL_PROPS     Cell properties
TEXT_LABEL_PROPS    Label properties
TEXT_BUTTON_PROPS   Button properties
TEXT_CHECK_PROPS    Checkbox properties
TEXT_RADIO_PROPS    Radio button properties
TEXT_TOOL_PROPS     Tool button properties
TEXT_POPUP_PROPS    Popup properties
TEXT_EDIT_PROPS     Editbox properties
TEXT_COMBO_PROPS    Combobox properties
TEXT_LIST_PROPS     Listbox properties
TEXT_SLIDER_PROPS   Slider properties
TEXT_LAYOUT         Layout
TEXT_LAYOUTS        Layouts
TEXT_BUTTONS        Buttons
TEXT_TEXT_WIDGETS   Text Widgets
TEXT_ITEM_WIDGETS   Item Widgets
TEXT_OTHER_WIDGETS  Other Widgets
TEXT_SELECT         Select
TEXT_VERT_LAYOUT    Vertical Layout
TEXT_HORZ_LAYOUT    Horizontal Layout
TEXT_GRID_LAYOUT    Grid Layout
TEXT_LABEL          Label
TEXT_PUSH_BUTTON    Push Button
TEXT_CHECK_BOX      Check Box
TEXT_RADIO_BUTTON   Radio Button
TEXT_TOOL_BUTTON    Tool Button
TEXT_ELEM_POPUP     PopUp Add Element
TEXT_POPUP_BUTTON   PopUp Button
TEXT_EDIT_BOX       Edit Box
TEXT_COMBO_BOX      Combo Box
TEXT_ELEM_LIST      ListBox Add Element
TEXT_LIST_BOX       List Box
TEXT_HORZ_SLIDER    Horizontal Slider
TEXT_VERT_SLIDER    Vertical Slider
TEXT_PROGRESS_BAR   Progress Bar
TEXT_TEXT_VIEW      Text View
TEXT_TABLE_VIEW     Table View
TEXT_IMAGE_VIEW     Image View
TEXT_BOX_FORMS      Forms
TEXT_BOX_INSPECTOR  Object inspector
TEXT_BOX_PROPEDIT   Property editor
TEXT_BOX_WIDGETS    Widgets
TEXT_TYPE           Type
TEXT_NAME           Name
TEXT_TOP            Top
TEXT_LEFT           Left
TEXT_BOTTOM         Bottom
TEXT_RIGHT          Right
TEXT_WIDTH          Width
TEXT_HPADDING       HorzPad
TEXT_VPADDING       VertPad
TEXT_HEIGHT         Height
TEXT_COLUMN         Column
TEXT_ROW            Row
TEXT_ALIGN          Align
TEXT_HALIGN         HAlign
TEXT_VALIGN         VAlign
TEXT_TEXT           Text
TEXT_MULTILINE      Multiline
TEXT_AUTOSELECT     Autoselect
TEXT_PASSMODE       Passmode
TEXT_TEXT_ALIGN     Text align
TEXT_MIN_WIDTH      Min width
TEXT_MIN_HEIGHT     Min height
TEXT_ICON           Icon
TEXT_ICON_PATH      Icon path
TEXT_ELEMENTS       Elements
TEXT_DEFAULT        default
TEXT_LOAD_IMAGE     Load image
TEXT_LOAD_ICON      Load icon
TEXT_LTYPE_SING     Single cell
TEXT_LTYPE_VERT     Vertical with %d rows
TEXT_LTYPE_HORZ     Horizontal with %d cols
TEXT_LTYPE_GRID     Grid %d cols x %d rows
TEXT_CELL_EMPTY     EmptyCell
TEXT_CELL_LABEL     LabelCell
TEXT_CELL_BUTTON    ButtonCell
TEXT_CELL_CHECK     CheckBoxCell
TEXT_CELL_RADIO     RadioButtonCell
TEXT_CELL_TOOL      ToolButtonCell
TEXT_CELL_POPUP     PopUpCell
TEXT_CELL_EDIT      EditBoxCell
TEXT_CELL_COMBO     ComboBoxCell
TEXT_CELL_LISTBOX   ListBoxCell
TEXT_CELL_SLIDER    SliderCell
TEXT_CELL_VSLIDER   VertSliderCell
TEXT_CELL_PROGRESS  ProgressCell
TEXT_CELL_TEXT      TextViewCell
TEXT_CELL_IMAGE     ImageViewCell
TEXT_CELL_TABLE     TableCell
TEXT_CELL_LAYOUT    LayoutCell

TIP_LAYOUT_NAME     Layout name. It will be useful to locate the layout at runtime.
TIP_CELL_NAME       Cell name. It will be useful to locate the cell at runtime.
TIP_TOP_MARGIN      Margin at top of layout (in px).
TIP_LEFT_MARGIN     Margin at left of layout (in px).
TIP_BOTTOM_MARGIN   Margin at bottom of layout (in px).
TIP_RIGHT_MARGIN    Margin at right of layout (in px).
TIP_COLUMN          Index of the column will be edited (0-based).
TIP_COLUMN_MARGIN   Internal margin at right of column (in px).
TIP_COLUMN_WIDTH    Column width (forced). If 0 will be set automatically.
TIP_ROW             Index of the row will be edited (0-based).
TIP_ROW_MARGIN      Internal margin at bottom of row (in px).
TIP_ROW_HEIGHT      Row height (forced). If 0 will be set automatically.
TIP_HALIGN          Horizontal alignment of the widget within the cell.
TIP_VALIGN          Vertical alignment of the widget within the cell.
TIP_LABEL_TEXT      The text that will be displayed on the label.
TIP_LABEL_MLINE     If set, the text will expand over multiple lines.
TIP_LABEL_MWIDTH    Text width. If 0 will be set automatically.
TIP_LABEL_ALIGN     Text alignment, if label widget if wider than the text.
TIP_BUTTON_TEXT     The text that will be displayed on the push button.
TIP_BUTTON_WIDTH    Minimum width of the push button, as long as the text is visible.
TIP_BUTTON_HPAD     Horizontal padding of the push button, -1 as default.
TIP_BUTTON_VPAD     Vertical padding of the push button, -1 as default.
TIP_CHECK_TEXT      The text that will be displayed to the right of the checkbox.
TIP_RADIO_TEXT      The text that will be displayed to the right of the radio button.
TIP_EDIT_ALIGN      Text alignment inside the editbox.
TIP_EDIT_MWIDTH     Editbox width. If 0 will be set automatically.
TIP_EDIT_PASSMODE   If set, the text will be hidden will be hidden by asterisks.
TIP_EDIT_AUTOSEL    If set, the text will be selected automatically when recibes the focus.
TIP_COMBO_ALIGN     Text alignment inside the combobox.
TIP_COMBO_MWIDTH    Combobox width. If 0 will be set automatically.
TIP_COMBO_PASSMODE  If set, the text will be hidden will be hidden by asterisks.
TIP_COMBO_AUTOSEL   If set, the text will be selected automatically when recibes the focus.
TIP_ELEMENT_ADD     Add a new element
TIP_ELEMENT_REMOVE  Remove current element
TIP_ELEMENT_CLEAR   Clear all elements
TIP_LIST_MWIDTH     Listbox width. If 0 will be set automatically.
TIP_LIST_MHEIGHT    Listbox height. If 0 will be set automatically.
TIP_SLIDER_MWIDTH   Slider width. If 0 will be set automatically.
