TEXT_OK             Ok
TEXT_CANCEL         Cancel
TEXT_COLUMNS        Columns
TEXT_ROWS           Rows
TEXT_NEW_SUBLAYOUT  A new sublayout will be placed in cell (%d, %d) of '%s' layout
TEXT_LAYOUT_PROPS   Layout properties
TEXT_COLUMN_PROPS   Column properties
TEXT_ROW_PROPS      Row properties
TEXT_LAYOUTS        Layouts
TEXT_BUTTONS        Buttons
TEXT_TEXT_WIDGETS   Text Widgets
TEXT_ITEM_WIDGETS   Item Widgets
TEXT_OTHER_WIDGETS  Other Widgets
TEXT_SELECT         Select
TEXT_VERT_LAYOUT    Vertical Layout
TEXT_HORZ_LAYOUT    Horizontal Layout
TEXT_GRID_LAYOUT    Grid Layout
TEXT_PUSH_BUTTON    Push Button
TEXT_TOOL_BUTTON    Tool Button
TEXT_RADIO_BUTTON   Radio Button
TEXT_CHECK_BOX      Check Box
TEXT_LABEL          Label
TEXT_EDIT_BOX       Edit Box
TEXT_COMBO_BOX      Combo Box
TEXT_TEXT_VIEW      Text View
TEXT_LIST_BOX       List Box
TEXT_POPUP_BUTTON   PopUp Button
TEXT_TABLE_VIEW     Table View
TEXT_IMAGE_VIEW     Image View
TEXT_HORZ_SLIDER    Horizontal Slider
TEXT_VERT_SLIDER    Vertical Slider
TEXT_PROGRESS_BAR   Progress Bar
TEXT_BOX_FORMS      Forms
TEXT_BOX_INSPECTOR  Object inspector
TEXT_BOX_PROPEDIT   Property editor
TEXT_BOX_WIDGETS    Widgets