TEXT_APP_TITLE      GTNAP Designer
TEXT_OK             Ok
TEXT_CANCEL         Cancel
TEXT_COLUMNS        Columns
TEXT_ROWS           Rows
TEXT_NEW_LABEL      A new label will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_BUTTON     A new push button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_CHECK      A new check box will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_RADIO      A new radio button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_TOOL       A new tool button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_POPUP      A new popup button will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_ELEM_POPUP A new element will be added to popup in cell '%s'
TEXT_NEW_ELEM_LIST  A new element will be added to listbox in cell '%s'
TEXT_NEW_EDIT       A new editbox will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_COMBO      A new combo box will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_LISTBOX    A new listbox will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_SLIDER     A new slider will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_VSLIDER    A new vertical slider will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_PROGRESS   A new progressbar will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_CUSTOMVIEW A new custom view will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_SCROLLVIEW A new scroll view will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_TEXTVIEW   A new textview will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_IMAGEVIEW  A new imageview will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_TABLEVIEW  A new tableview will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_HLINE      A new horizontal separator will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_VLINE      A new vertical separator will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_SUBLAYOUT  A new sublayout will be placed in cell (%d, %d) of '%s' layout
TEXT_NEW_FORM       A new form will be created with this filename and properties
TEXT_PROPS_FORM     Change the filename and forms properties

TEXT_LAYOUT_PROPS   Layout properties
TEXT_COLUMN_PROPS   Column properties
TEXT_ROW_PROPS      Row properties
TEXT_CELL_PROPS     Cell properties
TEXT_LABEL_PROPS    Label properties
TEXT_BUTTON_PROPS   Button properties
TEXT_CHECK_PROPS    Checkbox properties
TEXT_RADIO_PROPS    Radio button properties
TEXT_TOOL_PROPS     Tool button properties
TEXT_POPUP_PROPS    Popup properties
TEXT_EDIT_PROPS     Editbox properties
TEXT_COMBO_PROPS    Combobox properties
TEXT_LIST_PROPS     Listbox properties
TEXT_SLIDER_PROPS   Slider properties
TEXT_VSLIDER_PROPS  VertSlider properties
TEXT_PROGRESS_PROPS Progressbar properties
TEXT_VIEW_PROPS     Custom view properties
TEXT_SVIEW_PROPS    Scroll view properties
TEXT_TEXT_PROPS     Textview properties
TEXT_IMAGE_PROPS    Imageview properties
TEXT_TABLE_PROPS    Tableview properties
TEXT_HLINE_PROPS    HorzLine properties
TEXT_VLINE_PROPS    VertLine properties
TEXT_LAYOUT         Layout
TEXT_LAYOUTS        Layouts
TEXT_BUTTONS        Buttons
TEXT_TEXT_WIDGETS   Text Widgets
TEXT_ITEM_WIDGETS   Item Widgets
TEXT_DISPLAY_WIDGETS Display Widgets
TEXT_OTHER_WIDGETS  Other Widgets
TEXT_SELECT         Select
TEXT_SINGLE_LAYOUT  Single Layout
TEXT_VERT_LAYOUT    Vertical Layout
TEXT_HORZ_LAYOUT    Horizontal Layout
TEXT_GRID_LAYOUT    Grid Layout
TEXT_LABEL          Label
TEXT_PUSH_BUTTON    Push Button
TEXT_CHECK_BOX      Check Box
TEXT_RADIO_BUTTON   Radio Button
TEXT_TOOL_BUTTON    Tool Button
TEXT_ELEM_POPUP     PopUp Add Element
TEXT_POPUP_BUTTON   PopUp Button
TEXT_EDIT_BOX       Edit Box
TEXT_COMBO_BOX      Combo Box
TEXT_ELEM_LIST      ListBox Add Element
TEXT_LIST_BOX       List Box
TEXT_HORZ_SLIDER    Horizontal Slider
TEXT_VERT_SLIDER    Vertical Slider
TEXT_PROGRESS_BAR   Progress Bar
TEXT_HORZ_LINE      Horizontal Line
TEXT_VERT_LINE      Vertical Line
TEXT_CUSTOM_VIEW    Custom View
TEXT_SCROLL_VIEW    Scroll View
TEXT_TEXT_VIEW      Text View
TEXT_IMAGE_VIEW     Image View
TEXT_TABLE_VIEW     Table View
TEXT_VIEW           View
TEXT_FORM           Form
TEXT_FORM_PROPS     Form properties
TEXT_BOX_FORMS      Forms
TEXT_BOX_FORM_BOX   Forms box
TEXT_BOX_WIDGET_BOX Widgets box
TEXT_BOX_INSPECTOR  Object inspector
TEXT_BOX_PROPEDIT   Property editor
TEXT_BOX_WIDGETS    Widgets
TEXT_OBJECT         Object
TEXT_TYPE           Type
TEXT_NAME           Name
TEXT_TOP            Top
TEXT_LEFT           Left
TEXT_BOTTOM         Bottom
TEXT_RIGHT          Right
TEXT_WIDTH          Width
TEXT_LENGTH         Length
TEXT_HPADDING       HorzPad
TEXT_VPADDING       VertPad
TEXT_HEIGHT         Height
TEXT_COLUMN         Column
TEXT_ROW            Row
TEXT_ALIGN          Align
TEXT_HALIGN         HAlign
TEXT_VALIGN         VAlign
TEXT_DALIGN         DAlign
TEXT_SCALE          Scale
TEXT_TEXT           Text
TEXT_TOOLTIP        Tooltip
TEXT_TITLE          Title
TEXT_BORDER         Border
TEXT_GROUP          Group
TEXT_MULTILINE      Multiline
TEXT_AUTOSELECT     Autoselect
TEXT_PASSMODE       Passmode
TEXT_RESIZABLE      Resizable
TEXT_TABSTOP        Tabstop
TEXT_TABORDER       Taborder
TEXT_BACKGROUND     Background
TEXT_LIGHT          Light
TEXT_DARK           Dark

TEXT_TEXT_ALIGN     TAlign
TEXT_MIN_WIDTH      Min width
TEXT_MAX_WIDTH      Max width
TEXT_MIN_HEIGHT     Min height
TEXT_READ_ONLY      Read only
TEXT_ICON           Icon
TEXT_IMAGE          Image
TEXT_ICON_PATH      Icon path
TEXT_IMAGE_PATH     Image path
TEXT_ELEMENTS       Elements
TEXT_DEFAULT        default
TEXT_LOAD_IMAGE     Load image
TEXT_LOAD_ICON      Load icon
TEXT_PREV_IMAGE     Image preview
TEXT_LTYPE_SING     Single cell
TEXT_LTYPE_VERT     Vertical with %d rows
TEXT_LTYPE_HORZ     Horizontal with %d cols
TEXT_LTYPE_GRID     Grid %d cols x %d rows
TEXT_CELL_EMPTY     EmptyCell
TEXT_CELL_LABEL     LabelCell
TEXT_CELL_BUTTON    ButtonCell
TEXT_CELL_CHECK     CheckBoxCell
TEXT_CELL_RADIO     RadioButtonCell
TEXT_CELL_TOOL      ToolButtonCell
TEXT_CELL_POPUP     PopUpCell
TEXT_CELL_EDIT      EditBoxCell
TEXT_CELL_COMBO     ComboBoxCell
TEXT_CELL_LISTBOX   ListBoxCell
TEXT_CELL_SLIDER    SliderCell
TEXT_CELL_VSLIDER   VertSliderCell
TEXT_CELL_PROGRESS  ProgressCell
TEXT_CELL_VIEW      ViewCell
TEXT_CELL_SVIEW     ScrollViewCell
TEXT_CELL_TEXT      TextViewCell
TEXT_CELL_IMAGE     ImageViewCell
TEXT_CELL_TABLE     TableCell
TEXT_CELL_HLINE     HLineCell
TEXT_CELL_VLINE     VLineCell
TEXT_CELL_LAYOUT    LayoutCell
TEXT_FILE           File
TEXT_FILENAME       Filename
TEXT_DESCRIPTION    Description
TEXT_EDIT           Edit
TEXT_UNDO           Undo
TEXT_REDO           Redo
TEXT_CUT            Cut
TEXT_COPY           Copy
TEXT_PASTE          Paste
TOOLBAR_OPEN        Open forms folder
TOOLBAR_SAVE        Save all forms
TOOLBAR_NEW         Add new form
TOOLBAR_NEW_FORM    New form
TOOLBAR_PROPS       Form properties
TOOLBAR_SIMULATE    Simulate form
TOOLBAR_RESIZABLE   Simulate resizable form
TOOLBAR_LSKEL       Layout design view
TOOLBAR_REMOVE      Remove current form
TEXT_QUIT           Quit
TEXT_OPEN_CAPTION   Select the form folder you want to work with.
TEXT_ERROR_NAME     Error in form name
TEXT_NAME_EXISTS    Form name '%s' already exists
TEXT_REMOVE_COLC    Remove column
TEXT_REMOVE_ROWC    Remove row
TEXT_NO_REMOVE_COL  Column '0' of layout '%s' can't be removed. At least, one column is required in the layout.
TEXT_NO_REMOVE_ROW  Row '0' of layout '%s' can't be removed. At least, one row is required in the layout.
TEXT_REMOVE_FORM    The form '%s' will be deleted from the disk. This operation is irreversible. Do you really want to continue?
TEXT_REMOVE_COL     The column '%d' of layout '%s' will be removed. Do you really want to continue?
TEXT_REMOVE_ROW     The row '%d' of layout '%s' will be removed. Do you really want to continue?
TEXT_FORM_REMOVE    Remove form
TEXT_COL_REMOVE     Remove column
TEXT_ROW_REMOVE     Remove row
TEXT_SAVE_CHANGES   Save changes
TEXT_DISC_CHANGES   Discard changes
TEXT_UNSAVE_CHANGES There are unsaved changes
TEXT_UNSAVED1       There are unsaved changes in your current forms.\nChanges will be lost if you open another project folder.\nDo you want to save your changes?
TEXT_UNSAVED2       There are unsaved changes in your current forms.\nChanges will be lost if you close the application.\nDo you want to save your changes?
TEXT_UNDO_STACK     Undo stack
TEXT_PROMOTE        Promote

TIP_LAYOUT_NAME     Layout name. It will be useful to locate the layout at runtime.
TIP_CELL_NAME       Cell name. It will be useful to locate the cell at runtime.
TIP_CELL_TABSTOP    If uncheck, this cell cannot be selected using the [TAB] key.
TIP_TOP_PADDING     Padding at top of cell (in px).
TIP_LEFT_PADDING    Padding at left of cell (in px).
TIP_BOTTOM_PADDING  Padding at bottom of cell (in px).
TIP_RIGHT_PADDING   Padding at right of cell (in px).
TIP_TOP_MARGIN      Margin at top of layout (in px).
TIP_LEFT_MARGIN     Margin at left of layout (in px).
TIP_BOTTOM_MARGIN   Margin at bottom of layout (in px).
TIP_RIGHT_MARGIN    Margin at right of layout (in px).
TIP_BORDER          Enable the border line with solid color.
TIP_BACKGROUND      Enable the background fill with solid color.
TIP_GROUP           Enable the group frame, with standard color.
TIP_GROUP_TITLE     Text to show at top of the group frame.
TIP_LIGHT_COLOR     Color for light-mode themes.
TIP_DARK_COLOR      Color for dark-mode themes.
TIP_COLUMN          Index of the column will be edited (0-based).
TIP_COLUMN_MARGIN   Internal margin at right of column (in px).
TIP_COLUMN_WIDTH    Column width (forced). If 0 will be set automatically.
TIP_ROW             Index of the row will be edited (0-based).
TIP_ROW_MARGIN      Internal margin at bottom of row (in px).
TIP_ROW_HEIGHT      Row height (forced). If 0 will be set automatically.
TIP_HALIGN          Horizontal alignment of the widget within the cell.
TIP_VALIGN          Vertical alignment of the widget within the cell.
TIP_LABEL_TEXT      The text that will be displayed on the label.
TIP_LABEL_MLINE     If set, the text will expand over multiple lines.
TIP_LABEL_MWIDTH    Text width. If 0 will be set automatically.
TIP_LABEL_ALIGN     Text alignment, if label widget if wider than the text.
TIP_BUTTON_TEXT     The text that will be displayed on the push button.
TIP_BUTTON_TOOLTIP  The tooltip text that will be displayed when the mouse is over the button.
TIP_BUTTON_WIDTH    Minimum width of the push button, as long as the text is visible.
TIP_BUTTON_HPAD     Horizontal padding of the push button, -1 as default.
TIP_BUTTON_VPAD     Vertical padding of the push button, -1 as default.
TIP_CHECK_TEXT      The text that will be displayed to the right of the checkbox.
TIP_RADIO_TEXT      The text that will be displayed to the right of the radio button.
TIP_EDIT_ALIGN      Text alignment inside the editbox.
TIP_EDIT_MWIDTH     Editbox width.
TIP_EDIT_PASSMODE   If set, the text will be hidden will be hidden by asterisks.
TIP_EDIT_AUTOSEL    If set, the text will be selected automatically when recibes the focus.
TIP_COMBO_ALIGN     Text alignment inside the combobox.
TIP_COMBO_MWIDTH    Combobox width.
TIP_COMBO_PASSMODE  If set, the text will be hidden will be hidden by asterisks.
TIP_COMBO_AUTOSEL   If set, the text will be selected automatically when recibes the focus.
TIP_ELEMENT_ADD     Add a new element
TIP_ELEMENT_REMOVE  Remove current element
TIP_ELEMENT_CLEAR   Remove all elements
TIP_COLUMN_ADD      Add a new column
TIP_COLUMN_REMOVE   Remove current column
TIP_COLUMN_CLEAR    Remove all columns
TIP_LIST_MWIDTH     Listbox width.
TIP_LIST_MHEIGHT    Listbox height.
TIP_SLIDER_MWIDTH   Slider width.
TIP_SLIDER_MHEIGHT  Slider height.
TIP_PROGRESS_MWIDTH Progress width.
TIP_HLINE_LENGTH    Horizontal line length.
TIP_VLINE_LENGTH    Vertical line length.

TIP_VIEW_MWIDTH     View width.
TIP_VIEW_MHEIGHT    View height.
TIP_TEXT_MWIDTH     Textview width.
TIP_TEXT_MHEIGHT    Textview height.
TIP_IMAGE_MWIDTH    Imageview width.
TIP_IMAGE_MHEIGHT   Imageview height.
TIP_IMAGE_SCALE     Image scale mode (Aspect recommended).
TIP_TABLE_MWIDTH    Tableview width.
TIP_TABLE_MHEIGHT   Tableview height.
TIP_COLUMN_TITLE    Column title.
TIP_COLUMN_HALIGN   Column header alignment.
TIP_COLUMN_DALIGN   Column data alignment.
TIP_COLUMN_TWIDTH   Column width.
TIP_COLUMN_MINWIDTH Column minimum width.
TIP_COLUMN_MAXWIDTH Column maximum width.
TIP_COLUMN_RESIZE   Column is resizable.
TIP_COLUMN_LEFT     Insert a new column at left of current column
TIP_COLUMN_RIGHT    Insert a new column at right of current column
TIP_COLUMN_DELETE   Delete current column
TIP_COLUMN_EXPAND   Mark/unmark this column as expansible
TIP_ROW_TOP         Insert a new row at top of current row
TIP_ROW_BOTTOM      Insert a new row at bottom of current row
TIP_ROW_DELETE      Delete current row
TIP_ROW_EXPAND      Mark/unmark this row as expansible
TIP_PROMOTE_LEFT    Promote this layout to a left cell
TIP_PROMOTE_RIGHT   Promote this layout to a right cell
TIP_PROMOTE_TOP     Promote this layout to a top cell
TIP_PROMOTE_BOTTOM  Promote this layout to a bottom cell
TIP_TABORDER_COLS   The tabstops will be moved column by column
TIP_TABORDER_ROWS   The tabstops will be moved row by row
